name: kegg_env
channels:
  - conda-forge
  - pytorch
  - pyg
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas>=2.0.0
  - numpy>=1.20.0
  - scipy>=1.7.0
  - networkx>=3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - openpyxl>=3.0.0
  - pyyaml>=6.0
  - tqdm>=4.60.0
  - joblib>=1.0.0
  - requests>=2.25.0
  - ipython>=8.0.0
  - biopython>=1.80
  - pytorch>=2.0.0
  - pytorch-cuda=12.4
  - pip:
    - dgl>=2.0.0
    - torch-geometric>=2.0.0
    - plotly>=5.0.0
    - pyvis>=0.3.0
    - rdkit>=2023.0.0
    - tensorboard>=2.0.0